#!/bin/sh

ln -svfT ../dotfiles/compton.conf ~/.config/compton.conf
ln -svfT ../dotfiles/git ~/.config/git
ln -svfT ../dotfiles/herbstluftwm ~/.config/herbstluftwm
ln -svfT ../dotfiles/lilyterm ~/.config/lilyterm

ln -svfT dotfiles/bashrc ~/.bashrc
ln -svfT dotfiles/screenrc ~/.screenrc
ln -svfT dotfiles/Xresources ~/.Xresources
ln -svfT dotfiles/vimrc ~/.vimrc
